### ISSUE TITLE
Implement timeout for connections 

### ISSUE THREAD

**Issue by MortezaBashsiz** [MortezaBashsiz/nipovpn#79]
### Issue
Currently, there is no timeout for closing stalled connections. So if a connection stalled by some reason, the program will keep the connection alive till client or server close it and if client or server do not close the connection, it will be open forever in the program.

We need to have a timeout option configurable in config file and then check it in program, if there is no new action on socket and the time is over, then close the connection

**Comment by Ali-Nasrolahi** [comment]
Hi @MortezaBashsiz,

I like your project, and would like to be a help for future developments if you like :)

I've looked into this particular issue and like to contribute to it ( If you haven't already fixed it ).
Just one question:
- Do you have any preference/idea or any type of lead for the implementation?
> I did a real quick search, and thought Boost's `timers` (like `deadline_timer` in `tcp*` sources) somehow might be useful for blocking read operations in TCP classes (like `doRead` and `handleRead`).

Thanks,
Ali

P.S: I had a few questions about the source code, should I ask them in new/dedicated issue? Or maybe in `Discussion` section of the repository (It is disabled right now).

**Comment by MortezaBashsiz** [comment]
@Ali-Nasrolahi 
Thanks a lot for your comment
I enabled the discussion, then you can ask your questions there if you want
About the deadline_timer I already used them in code (**[Here](https://github.com/MortezaBashsiz/nipovpn/blob/0248959624cc35fc038ac44f0cff1a2a68c8e49b/src/tcpclient.cpp#L127)** for example in TCPClient::doRead) but it is just for reading all data from socket

For purpose of connection timeout, we need to implement it like following

- Add configurable directive in config file
- Start the timer synchronously when connection is established
- Reset the timer in each read or write actions
- At the end, wait till timer is over and gracefully close the socket

This is the idea which came to my mind, but it could be better in different way.

**Comment by Ali-Nasrolahi** [comment]
Great!

How does the following implementation sound to you?

- Including new general configuration directive similar to `timeWait` option
- Adding a `deadline_timer` to `TCPClient` and `TCPConnection` classes; and  before every I/O operation,  the timer resets by `_resetTimer()` private method. 
- In case of a timeout, expiration's handler logs the event and closes associated `socket`'s handle to prevent further I/O.

Please let me know what you think.
Thanks

P.S:

During code examination for mentioned issue, I've noticed you have used timers in `tcpconnection.cpp:doRead()` and `tcpclient.cpp:doRead()` to ,what I've understood, wait for the input. Probably I am mistaken, but what's the reason behind using a timer instead of a `std::this_thread::sleep_for` to accomplish similar behavior. (I assume there must be something to do with `io_context`, but I'm not sure)

**Comment by MortezaBashsiz** [comment]
TBH It is not matter how we implement it at first place, We need something stable, safe, and functional. Then we will spend time to make it better. I think you can try to implement and test if it works or not.

To have a better overview of the reason why I used timers there, please read this issue #62

**Comment by MortezaBashsiz** [comment]
Resolved
